player_name_format: "%player_displayname%"
#死亡消息展示的地方，支持chat（聊天栏）和action_bar（物品栏上方）和all（同时chat和action_bar），默认为chat
death_message_type: chat
proxy: false
death_message:
  death-attack-anvil:
    - "%dead_player%被铁砧砸中了"
  death-attack-anvil-player:
    - "%dead_player%在与%killer%战斗时被坠落的铁砧压扁了"
  death-attack-arrow:
    - "%dead_player%被%killer%射杀"
  death-attack-arrow-item:
    - "%dead_player%被%killer%用%kill_item%射杀"
  death-attack-badRespawnPoint-message:
    - "%dead_player%被%killer%杀死了"
  bad-respawn-point:
    - "[刻意的游戏设计]"
  death-attack-cactus:
    - "%dead_player%被戳死了"
  death-attack-cactus-player:
    - "%dead_player%在试图逃离%killer%时撞上了仙人掌"
  death-attack-cramming:
    - "%dead_player%因被过度挤压而死"
  death-attack-cramming-player:
    - "%dead_player%被%killer%挤扁了"
  death-attack-dragonBreath:
    - "%dead_player%被龙息烤熟了"
  death-attack-dragonBreath-player:
    - "%dead_player%被%killer%的龙息烤熟了"
  death-attack-drown:
    - "%dead_player%淹死了"
  death-attack-drown-player:
    - "%dead_player%在试图逃离%killer%时淹死了"
  death-attack-dryout:
    - "%dead_player%因脱水而死"
  death-attack-dryout-player:
    - "%dead_player%在试图逃离%killer%时因脱水而死"
  death-attack-even_more_magic:
    - "%dead_player%被不为人知的魔法杀死了"
  death-attack-explosion:
    - "%dead_player%爆炸了"
  death-attack-explosion-player:
    - "%dead_player%被%killer%炸死了"
  death-attack-explosion-player-item:
    - "%dead_player%被%killer%用%kill_item%炸死了"
  death-attack-fall:
    - "%dead_player%落地过猛"
  death-attack-fall-player:
    - "%dead_player%在试图逃离%killer%时落地过猛"
  death-attack-fallingBlock:
    - "%dead_player%被下落的方块压扁了"
  death-attack-fallingBlock-player:
    - "%dead_player%在与%killer%战斗时被下落的方块压扁了"
  death-attack-fallingStalactite:
    - "%dead_player%被坠落的钟乳石刺穿了"
  death-attack-fallingStalactite-player:
    - "%dead_player%在与%killer%战斗时被坠落的钟乳石刺穿了"
  death-attack-fireball:
    - "%dead_player%被%killer%用火球烧死了"
  death-attack-fireball-item:
    - "%dead_player%被%killer%用%kill_item%发射的火球烧死了"
  death-attack-fireworks:
    - "%dead_player%随着一声巨响消失了"
  death-attack-fireworks-item:
    - "%dead_player%随着%killer%用%kill_item%发射的烟花发出的巨响消失了"
  death-attack-fireworks-player:
    - "%dead_player%在与%killer%战斗时随着一声巨响中消失了"
  death-attack-flyIntoWall:
    - "%dead_player%感受到了动能"
  death-attack-flyIntoWall-player:
    - "%dead_player%在试图逃离%killer%时感受到了动能"
  death-attack-freeze:
    - "%dead_player%被冻死了"
  death-attack-freeze-player:
    - "%dead_player%被%killer%冻死了"
  death-attack-generic:
    - "%dead_player%死了"
  death-attack-generic-player:
    - "%dead_player%死于%killer%"
  death-attack-genericKill:
    - "%dead_player%被杀死了"
  death-attack-genericKill-player:
    - "%dead_player%在与%killer%战斗时被杀死了"
  death-attack-hotFloor:
    - "%dead_player%发现了地板是熔岩做的"
  death-attack-hotFloor-player:
    - "%dead_player%因%killer%而步入危险之地"
  death-attack-inFire:
    - "%dead_player%浴火焚身"
  death-attack-inFire-player:
    - "%dead_player%在与%killer%战斗时踏入了火中"
  death-attack-inWall:
    - "%dead_player%在墙里窒息而亡"
  death-attack-inWall-player:
    - "%dead_player%在与%killer%战斗时在墙里窒息而亡"
  death-attack-indirectMagic:
    - "%dead_player%被%killer%使用的魔法杀死了"
  death-attack-indirectMagic-item:
    - "%dead_player%被%killer%用%kill_item%杀死了"
  death-attack-lava:
    - "%dead_player%试图在熔岩里游泳"
  death-attack-lava-player:
    - "%dead_player%在逃离%killer%时试图在熔岩里游泳"
  death-attack-lightningBolt:
    - "%dead_player%被闪电击中"
  death-attack-lightningBolt-player:
    - "%dead_player%在与%killer%战斗时被闪电击中"
  death-attack-magic:
    - "%dead_player%被魔法杀死了"
  death-attack-magic-player:
    - "%dead_player%在试图逃离%killer%时被魔法杀死了"
  death-attack-message-too-long:
    - "死亡文本过长，原文：%s"
  death-attack-mob:
    - "%dead_player%被%killer%杀死了"
  death-attack-mob-item:
    - "%dead_player%被%killer%用%kill_item%杀死了"
  death-attack-onFire:
    - "%dead_player%被烧死了"
  death-attack-onFire-player:
    - "%dead_player%在与%killer%战斗时被烤得酥脆"
  death-attack-onFire-item:
    - "%dead_player%在与持有%kill_item%的%killer%战斗时被烤得酥脆"
  death-attack-outOfWorld:
    - "%dead_player%掉出了这个世界"
  death-attack-outOfWorld-player:
    - "%dead_player%与%killer%不共戴天"
  death-attack-outsideBorder:
    - "%dead_player%脱离了这个世界"
  death-attack-outsideBorder-player:
    - "%dead_player%在与%killer%战斗时脱离了这个世界"
  death-attack-player:
    - "%dead_player%被%killer%杀死了"
  death-attack-player-item:
    - "%dead_player%被%killer%用%kill_item%杀死了"
  death-attack-sonic_boom:
    - "%dead_player%被一道音波尖啸抹除了"
  death-attack-sonic_boom-item:
    - "%dead_player%在试图逃离持有%killer%的%kill_item%时被一道音波尖啸抹除了"
  death-attack-sonic_boom-player:
    - "%dead_player%在试图逃离%killer%时被一道音波尖啸抹除了"
  death-attack-stalagmite:
    - "%dead_player%被石笋刺穿了"
  death-attack-stalagmite-player:
    - "%dead_player%在与%killer%战斗时被石笋刺穿了"
  death-attack-starve:
    - "%dead_player%饿死了"
  death-attack-starve-player:
    - "%dead_player%在与%killer%战斗时饿死了"
  death-attack-sting:
    - "%dead_player%被蛰死了"
  death-attack-sting-item:
    - "%dead_player%被%killer%使用%kill_item%蛰死了"
  death-attack-sting-player:
    - "%dead_player%被%killer%蛰死了"
  death-attack-sweetBerryBush:
    - "%dead_player%被甜浆果丛刺死了"
  death-attack-sweetBerryBush-player:
    - "%dead_player%在试图逃离%killer%时被甜浆果丛刺死了"
  death-attack-thorns:
    - "%dead_player%在试图伤害%killer%时被杀"
  death-attack-thorns-item:
    - "%dead_player%在试图伤害%killer%时被%kill_item%杀死"
  death-attack-thrown:
    - "%dead_player%被%killer%给砸死了"
  death-attack-thrown-item:
    - "%dead_player%被%killer%用%kill_item%给砸死了"
  death-attack-trident:
    - "%dead_player%被%killer%刺穿了"
  death-attack-trident-item:
    - "%dead_player%被%killer%用%kill_item%刺穿了"
  death-attack-wither:
    - "%dead_player%凋零了"
  death-attack-wither-player:
    - "%dead_player%在与%killer%战斗时凋零了"
  death-attack-witherSkull:
    - "%dead_player%被%killer%发射的头颅射杀"
  death-attack-witherSkull-item:
    - "%dead_player%被%killer%使用%kill_item%发射的头颅射杀"
  death-attack-mace_smash:
    - '%dead_player%被%killer%一锤毙命'
  death-attack-mace_smash-item:
    - '%dead_player%被%killer%用%kill_item%一锤毙命'
  death-fell-accident-generic:
    - "%dead_player%从高处摔了下来"
  death-fell-accident-ladder:
    - "%dead_player%从梯子上摔了下来"
  death-fell-accident-other_climbable:
    - "%dead_player%在攀爬时摔了下来"
  death-fell-accident-scaffolding:
    - "%dead_player%从脚手架上摔了下来"
  death-fell-accident-twisting_vines:
    - "%dead_player%从缠怨藤上摔了下来"
  death-fell-accident-vines:
    - "%dead_player%从藤蔓上摔了下来"
  death-fell-accident-weeping_vines:
    - "%dead_player%从垂泪藤上摔了下来"
  death-fell-assist:
    - "%dead_player%因为%killer%注定要摔死"
  death-fell-assist-item:
    - "%dead_player%因为%killer%使用了%kill_item%注定要摔死"
  death-fell-finish:
    - "%dead_player%摔伤得太重并被%killer%完结了生命"
  death-fell-finish-item:
    - "%dead_player%摔伤得太重并被%killer%用%kill_item%完结了生命"
  death-fell-killer:
    - "%dead_player%注定要摔死"
plugin_message:
  command_reload: "&a插件重载完毕"
  only_player: "&c只有玩家才能使用此命令"
  filter_on: "&a已开启死亡消息屏蔽"
  filter_off: "&a已关闭死亡消息屏蔽"