helloMessage:
  - "&b新人&c&l来了奥！"
joinMessage:
  - "{}&b&l来了喵~"
quitMessage:
  - "{}&b&l走了喵~"
death_attack_anvil:
  - "%1$s被坠落的铁砧压扁了"
death_attack_anvil_player:
  - "%1$s在与%2$s战斗时被坠落的铁砧压扁了"
death_attack_arrow:
  - "%1$s被%2$s射杀"
death_attack_arrow_item:
  - "%1$s被%2$s用%3$s射杀"
death_attack_badRespawnPoint_message:
  - "%1$s被%2$s杀死了"
bedRespawnPoint:
  - "[刻意的游戏设计]"
death_attack_cactus:
  - "%1$s被戳死了"
death_attack_cactus_player:
  - "%1$s在试图逃离%2$s时撞上了仙人掌"
death_attack_cramming:
  - "%1$s因被过度挤压而死"
death_attack_cramming_player:
  - "%1$s被%2$s挤扁了"
death_attack_dragonBreath:
  - "%1$s被龙息烤熟了"
death_attack_dragonBreath_player:
  - "%1$s被%2$s的龙息烤熟了"
death_attack_drown:
  - "%1$s淹死了"
death_attack_drown_player:
  - "%1$s在试图逃离%2$s时淹死了"
death_attack_dryout:
  - "%1$s因脱水而死"
death_attack_dryout_player:
  - "%1$s在试图逃离%2$s时因脱水而死"
death_attack_even_more_magic:
  - "%1$s被不为人知的魔法杀死了"
death_attack_explosion:
  - "%1$s爆炸了"
death_attack_explosion_player:
  - "%1$s被%2$s炸死了"
death_attack_explosion_player_item:
  - "%1$s被%2$s用%3$s炸死了"
death_attack_fall:
  - "%1$s落地过猛"
death_attack_fall_player:
  - "%1$s在试图逃离%2$s时落地过猛"
death_attack_fallingBlock:
  - "%1$s被下落的方块压扁了"
death_attack_fallingBlock_player:
  - "%1$s在与%2$s战斗时被下落的方块压扁了"
death_attack_fallingStalactite:
  - "%1$s被坠落的钟乳石刺穿了"
death_attack_fallingStalactite_player:
  - "%1$s在与%2$s战斗时被坠落的钟乳石刺穿了"
death_attack_fireball:
  - "%1$s被%2$s用火球烧死了"
death_attack_fireball_item:
  - "%1$s被%2$s用%3$s发射的火球烧死了"
death_attack_fireworks:
  - "%1$s随着一声巨响消失了"
death_attack_fireworks_item:
  - "%1$s随着%2$s用%3$s发射的烟花发出的巨响消失了"
death_attack_fireworks_player:
  - "%1$s在与%2$s战斗时随着一声巨响中消失了"
death_attack_flyIntoWall:
  - "%1$s感受到了动能"
death_attack_flyIntoWall_player:
  - "%1$s在试图逃离%2$s时感受到了动能"
death_attack_freeze:
  - "%1$s被冻死了"
death_attack_freeze_player:
  - "%1$s被%2$s冻死了"
death_attack_generic:
  - "%1$s死了"
death_attack_generic_player:
  - "%1$s死于%2$s"
death_attack_hotFloor:
  - "%1$s发现了地板是熔岩做的"
death_attack_hotFloor_player:
  - "%1$s因%2$s而步入危险之地"
death_attack_inFire:
  - "%1$s浴火焚身"
death_attack_inFire_player:
  - "%1$s在与%2$s战斗时踏入了火中"
death_attack_inWall:
  - "%1$s在墙里窒息而亡"
death_attack_inWall_player:
  - "%1$s在与%2$s战斗时在墙里窒息而亡"
death_attack_indirectMagic:
  - "%1$s被%2$s使用的魔法杀死了"
death_attack_indirectMagic_item:
  - "%1$s被%2$s用%3$s杀死了"
death_attack_lava:
  - "%1$s试图在熔岩里游泳"
death_attack_lava_player:
  - "%1$s在逃离%2$s时试图在熔岩里游泳"
death_attack_lightningBolt:
  - "%1$s被闪电击中"
death_attack_lightningBolt_player:
  - "%1$s在与%2$s战斗时被闪电击中"
death_attack_magic:
  - "%1$s被魔法杀死了"
death_attack_magic_player:
  - "%1$s在试图逃离%2$s时被魔法杀死了"
death_attack_mob:
  - "%1$s被%2$s杀死了"
death_attack_mob_item:
  - "%1$s被%2$s用%3$s杀死了"
death_attack_onFire:
  - "%1$s被烧死了"
death_attack_onFire_player:
  - "%1$s在与%2$s战斗时被烤得酥脆"
death_attack_outOfWorld:
  - "%1$s掉出了这个世界"
death_attack_outOfWorld_player:
  - "%1$s与%2$s不共戴天"
death_attack_player:
  - "%1$s被%2$s杀死了"
death_attack_player_item:
  - "%1$s被%2$s用%3$s杀死了"
death_attack_stalagmite:
  - "%1$s被石笋刺穿了"
death_attack_stalagmite_player:
  - "%1$s在与%2$s战斗时被石笋刺穿了"
death_attack_starve:
  - "%1$s饿死了"
death_attack_starve_player:
  - "%1$s在与%2$s战斗时饿死了"
death_attack_sting:
  - "%1$s被蛰死了"
death_attack_sting_player:
  - "%1$s被%2$s蛰死了"
death_attack_sweetBerryBush:
  - "%1$s被甜浆果丛刺死了"
death_attack_sweetBerryBush_player:
  - "%1$s在试图逃离%2$s时被甜浆果丛刺死了"
death_attack_thorns:
  - "%1$s在试图伤害%2$s时被杀"
death_attack_thorns_item:
  - "%1$s在试图伤害%2$s时被%3$s杀死"
death_attack_thrown:
  - "%1$s被%2$s给砸死了"
death_attack_thrown_item:
  - "%1$s被%2$s用%3$s给砸死了"
death_attack_trident:
  - "%1$s被%2$s刺穿了"
death_attack_trident_item:
  - "%1$s被%2$s用%3$s刺穿了"
death_attack_wither:
  - "%1$s凋零了"
death_attack_wither_player:
  - "%1$s在与%2$s战斗时凋零了"
death_attack_witherSkull:
  - "%1$s被%2$s发射的头颅射杀"
death_fell_accident_generic:
  - "%1$s从高处摔了下来"
death_fell_accident_ladder:
  - "%1$s从梯子上摔了下来"
death_fell_accident_other_climbable:
  - "%1$s在攀爬时摔了下来"
death_fell_accident_scaffolding:
  - "%1$s从脚手架上摔了下来"
death_fell_accident_twisting_vines:
  - "%1$s从缠怨藤上摔了下来"
death_fell_accident_vines:
  - "%1$s从藤蔓上摔了下来"
death_fell_accident_weeping_vines:
  - "%1$s从垂泪藤上摔了下来"
death_fell_assist:
  - "%1$s因为%2$s注定要摔死"
death_fell_assist_item:
  - "%1$s因为%2$s使用了%3$s注定要摔死"
death_fell_finish:
  - "%1$s摔伤得太重并被%2$s完结了生命"
death_fell_finish_item:
  - "%1$s摔伤得太重并被%2$s用%3$s完结了生命"
death_fell_killer:
  - "%1$s注定要摔死"