name: DeathMessage
author: YufiriaMazenta
main: com.github.yufiriamazenta.deathmsg.DeathMessage
version: ${version}
api-version: 1.17
load: POSTWORLD
soft-depend: [ PlaceholderAPI ]
folia-supported: true
commands:
  deathmessagereload:
    aliases:
      - "dmrl"
    usage: "ยง4/dmrl"
    description: "reload death message"
    permission: "deathmessage.command.reload"
    permission-message: "ยง4you are not op !"
  deathmessagefilter:
    aliases:
      - 'dmf'
    permission: deathmessage.command.filter
permissions:
  deathmessage.command.filter:
    default: true
  deathmessage.perm.default:
    default: true