name: DeathMessage
author: YufiriaMazenta
main: pers.yufiria.deathmsg.DeathMessage
version: ${version}
api-version: 1.17
load: POSTWORLD
soft-depend: [ PlaceholderAPI ]
folia-supported: true
permissions:
  deathmessage.command.filter:
    default: true
  deathmessage.perm.default:
    default: true