name: DeathMessage
author: YufiriaMazenta
main: com.github.yufiriamazenta.deathmsg.DeathMessage
version: ${version}
api-version: 1.17
load: POSTWORLD
soft-depend: [ PlaceholderAPI ]
folia-supported: true
commands:
  deathmessagereload:
    aliases:
      - "dmrl"
    usage: "ยง4/dmrl"
    description: "reload death message"
    permission: "op"
    permission-message: "ยง4you are not op !"
  deathmessagefilter:
    aliases:
      - 'dmf'