name: DeathMessage
author: YufiriaMazenta
main: com.github.yufiriamazenta.DeathMessage
version: ${version}
api-version: 1.19
commands:
  deathmessagereload:
    aliases:
      - "dmrl"
    usage: "ยง4/dmrl"
    description: "reload death message"
    permission: "op"
    permission-message: "ยง4you are not op !"