name: DeathMessage
author: "Xin_biubiu"
main: com.mingxin.Main
version: 1.2.1
api-version: 1.19
commands:
  deathmessagereload:
    aliases:
      - "dmrl"
    usage: "ยง4/dmrl"
    description: "reload death message"
    permission: "op"
    permission-message: "ยง4you are not op !"